P10/Models/MugOrder.cs
using System;
using System.Collections.Generic;

namespace P10.Models
{
    public partial class MugOrder
    {
        public int Id { get; set; }
        public int Qty { get; set; }
        public string Color { get; set; }
        public int PokedexId { get; set; }
        public string CreatedBy { get; set; }
    }
}

P10/Controllers/MugOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using P10.Models;
using System.Dynamic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace P10.Controllers
{
	public class MugOrderController : Controller
	{
		private AppDbContext _dbContext;

		public MugOrderController(AppDbContext dbContext)
		{
			_dbContext = dbContext;
		}

		[Authorize]
		public IActionResult Index()
		{
			DbSet<MugOrder> dbs = _dbContext.MugOrder;

			// TODO P10 Task 1-2 Modify code below so that only admin will see all orders and normal user will only see their own orders		
			// use the following code to help you:
			List<MugOrder> model = dbs.ToList(); // this code needs to be modified

			if (User.IsInRole("Admin"))
			{
				model = dbs.ToList();
			}
			else
			{
				var userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
				model = dbs.Where(mo => mo.CreatedBy == userid)
					 .ToList();
			}

			return View(model);
		}

		[Authorize]
		public IActionResult Create()
		{
			DbSet<Pokedex> dbs = _dbContext.Pokedex;
			var lstPokes =
				dbs.ToList<Pokedex>()
				   .OrderBy(p => p.Name)
				   .Select(
					   p =>
					   {
						   dynamic d = new ExpandoObject();
						   d.value = p.Id;
						   d.text = p.Name;
						   return d;
					   }
				   )
				   .ToList<dynamic>();
			ViewData["pokes"] = lstPokes;

			return View();
		}

		[HttpPost]
		[Authorize]
		public IActionResult Create(MugOrder mugOrder)
		{
			if (ModelState.IsValid)
			{
				DbSet<MugOrder> dbs = _dbContext.MugOrder;
				var userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
				mugOrder.CreatedBy = userid;
				dbs.Add(mugOrder);
				if (_dbContext.SaveChanges() == 1)
					TempData["Msg"] = "New order added!";
				else
					TempData["Msg"] = "Failed to update database!";
			}
			else
			{
				TempData["Msg"] = "Invalid information entered";
			}
			return RedirectToAction("Index");
		}

		[Authorize]
		public IActionResult Update(int id)
		{
			DbSet<MugOrder> dbs = _dbContext.MugOrder;
			MugOrder tOrder = dbs.Where(mo => mo.Id == id).FirstOrDefault();

			if (tOrder != null)
			{
				// other code...
				DbSet<Pokedex> dbsPoke = _dbContext.Pokedex;
				var lstPokes =
						dbsPoke.ToList<Pokedex>()
								.OrderBy(p => p.Name)
								.Select(
									p =>
									{
										dynamic d = new ExpandoObject();
										d.value = p.Id;
										d.text = p.Name;
										return d;
									}
								)
								.ToList<dynamic>();
				ViewData["pokes"] = lstPokes;

				return View(tOrder);
			}
			else
			{
				TempData["Msg"] = "Mug order not found!";
				return RedirectToAction("Index");
			}
		}

		[HttpPost]
		[Authorize]
		public IActionResult Update(MugOrder mugOrder)
		{
			if (ModelState.IsValid)
			{
				DbSet<MugOrder> dbs = _dbContext.MugOrder;
				MugOrder tOrder = dbs.Where(mo => mo.Id == mugOrder.Id)
									 .FirstOrDefault();

				if (tOrder != null)
				{
					tOrder.Color = mugOrder.Color;
					tOrder.PokedexId = mugOrder.PokedexId;
					tOrder.Qty = mugOrder.Qty;

					if (_dbContext.SaveChanges() == 1)
						TempData["Msg"] = "Mug order updated!";
					else
						TempData["Msg"] = "Failed to update database!";
				}
				else
				{
					TempData["Msg"] = "Mug order not found!";
					return RedirectToAction("Index");
				}
			}
			else
			{
				TempData["Msg"] = "Invalid information entered";
			}
			return RedirectToAction("Index");
		}

		[Authorize]
		public IActionResult Delete(int id)
		{
			DbSet<MugOrder> dbs = _dbContext.MugOrder;

			// TODO P10 Task 2-2 Use Where and FirstOrDefault LINQ-to-Entities method to retrieve the target MugOrder object
			//MugOrder tOrder = null; // this line needs to be modified to achieve Task 2-2
			MugOrder tOrder = dbs.Where(mo => mo.Id == id)
				.FirstOrDefault();

			if (tOrder != null)
			{
				// TODO P10 Task 2-3 Use Remove method to remove the found MugOrder object from DbSet
				dbs.Remove(tOrder);
				if (_dbContext.SaveChanges() == 1)
					TempData["Msg"] = "Mug order deleted!";
				else
					TempData["Msg"] = "Failed to update database!";
			}
			else
			{
				TempData["Msg"] = "Mug order not found!";
			}
			return RedirectToAction("Index");
		}

		[Authorize]
		public IActionResult LoadMug(string color, int pokedexid)
		{
			// TODO P10 Task 3-1 Complete the following code to create a new MugOrder and assign the pokedexid and color to the model properties
			//MugOrder model = null; // this line needs to be modified to achieve Task 3-1
			MugOrder model = new MugOrder();
			model.Color = color;
			model.PokedexId = pokedexid;

			// TODO P10 Task 3-2 Use PartialView method to return _ShowMug partial view and pass model object as the model
			//return null; // this line needs to be modified to achieve Task 3-2
			return PartialView("_ShowMug", model);
		}
	}
}

P10/Views/MugOrder/Create.cshtml
@model MugOrder

@{
	ViewBag.Title = "New Mug Order";
}

@section ScriptSection {
	<script>
		function AjaxLoadMug() {
			var color = "silver";

			// TODO P10 Task 3-3 Use .is method to identify which radio button is checked and use val() method to assign the radio button's value to variable color
			if ($("#rdColor1").is(":checked"))
			{
				color = $("#rdColor1").val();
			}
			else if ($("#rdColor2").is(":checked"))
			{
				color = $("#rdColor2").val();
			}

			// TODO P10 Task 3-4 Use val() method to assign the current selected value of ddlPoke to variable pokedexid
			//var pokedexid = "";
			var pokedexid = $("#ddlPoke").val();

			// TODO P10 Task 3-5 Form the url to call the LoadMug action
			//    Sample: /MugOrder/LoadMug?color=white&pokedexid=10
			var url = "/MugOrder/LoadShirt?color=" + color + "&pokedexid=" + pokedexid;

			// TODO P10 Task 3-6 Use jQuery load method to call the LoadMug action and replace the content of divPreview with the returned result
			// $("#divPreview").??
			$("#divPreview").load(url);
		}

		function CalcSubtotal() {
			var qty = $("#txtQty").val();
			var price = 10.00;
			var rate = 1;
			if (selectedCurrency == "USD")
				rate = rateUSD;
			var subtotal = qty * price * rate;
			$("#txtSubtotal").val(subtotal.toFixed(2));
		}

		$(document).ready(function () {
			// Call the AjaxLoadMug method when different radio button is selected
			$("#rdColor1").change(AjaxLoadMug);
			$("#rdColor2").change(AjaxLoadMug);

			// TODO P10 Task 3-7 Call the AjaxLoadMug method when ddlPoke selection changed by user
			$("#ddlPoke").change(AjaxLoadMug);
			// Calculate subtotal
			$("#txtQty").change(CalcSubtotal);

			$("form").submit(function () {
				confirm("Proceed? Press OK to confirm.");
			});
		});


	</script>
}

<h2>@ViewData["Title"]</h2>

<div class="row">
	<div class="col-sm-7">
		<form asp-controller="MugOrder" asp-action="Create" method="post" class="form-horizontal" role="form">
			<div class="form-horizontal">
				@{
					Html.RenderPartial("_MugOrder");
				}
				<div class="form-group">
					<label class="col-sm-3 control-label">Subtotal: </label>
					<div class="col-sm-6" style="padding-right:15px">
						<input id="txtSubtotal" class="form-control" readonly="readonly" value="0" />
					</div>
					<div class="col-sm-1" style="padding-left:0">
						@{
							Html.RenderPartial("_MugCurrencySelector");
						}
					</div>

				</div>
				<div class="form-group">
					<div class="col-sm-offset-3 col-sm-10">
						<input type="submit" value="Create" class="btn btn-default" />
					</div>
				</div>
			</div>
		</form>
	</div>
	<div id="divPreview" class="col-sm-5">
		@{
			// TODO P10 Task 3-8 Use Html.RenderPartial to render partial view _ShowMug with an empty MugOrder object as model
			// Html.RenderPartial...

			Html.RenderPartial("_ShowMug", new MugOrder());
		}
	</div>

</div>

P10/Views/MugOrder/Index.cshtml
@model List<MugOrder>

@{
    ViewBag.Title = "Mug Orders";
}

@section ScriptSection {
    <script>
        function ConfirmDelete() {
                /* TODO P10 Task 2-1 Use javascript confirm method to confirm the action to delete as follows:
                     1. The message displayed is "Are you sure you want to delete?"
                     2. If user click <Cancel>, which the confirm method return false then cancel the delete action
                 */
			if (confirm("Are you sure you want to delete?") == false) {
				event.preventDefault();
				event.stopPropagation();
				return false;
			}
		}

    </script>
}
<h2>Mug Orders</h2>

<span style="color:red">@TempData["Msg"]</span><br />
<p>
    <a asp-controller="MugOrder" asp-action="Create">Create New</a>
</p>

<table class="table">
    <tr>
        <th>Id</th>
        <th>Color</th>
        <th>Qty</th>
        @{ 
            // TODO P10 Task 1-3: Using User.IsInRole method to determine whether current user is Admin role and display the Created By column header
        }
		@if (User.IsInRole("Admin"))
		{
			<th>Created By</th>

		}
        <th>Actions</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.Id
            </td>
            <td>
                @item.Color
            </td>
            <td>
                @item.Qty
            </td>
            @{ 
              // TODO P10 Task 1-4: Using User.IsInRole method to determine whether current user is Admin role and display the Created By column data
            }
			@if (User.IsInRole("Admin"))
			{
				<th>Created By</th>

			}
            <td>
                <a asp-action="Update" asp-route-id="@item.Id">Update</a>
                <a asp-action="Delete" asp-route-id="@item.Id" onclick="return ConfirmDelete()">Delete</a>
            </td>
        </tr>
    }
</table>

P10/Views/MugOrder/Update.cshtml
@model MugOrder

@{
    ViewBag.Title = "Update Mug Order";
}

@section ScriptSection {
    <script>
        function AjaxLoadMug() {
            var color = $("#rdColor1").is(":checked") ? $("#rdColor1").val() : color = $("#rdColor2").val();
            var pokedexid = $("#ddlPoke").val();
            var url = "/MugOrder/LoadMug?color=" + color + "&pokedexid=" + pokedexid;
            $("#divPreview").load(url);
        }

        function CalcSubtotal() {
            var qty = $("#txtQty").val();
            var price = 10.00;
            var rate = 1;
            if (selectedCurrency == "USD")
                rate = rateUSD;
            var subtotal = qty * price * rate;
            $("#txtSubtotal").val(subtotal.toFixed(2));
        }

        $(document).ready(function () {
            // Reload the _ShowMug partial view whenever rdColor1, rdColor2 and ddlPoke changes
            $("#rdColor1").change(AjaxLoadMug);
            $("#rdColor2").change(AjaxLoadMug);
            $("#ddlPoke").change(AjaxLoadMug);

            // Calculate subtotal
            $("#txtQty").change(CalcSubtotal);

            $("form").submit(function () {
                confirm("Proceed? Press OK to confirm.");
            });
        });

    </script>
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-sm-7">
        <form asp-controller="MugOrder" asp-action="Update" method="post" class="form-horizontal" role="form">
            <div class="form-horizontal">
                <div class="form-group">
                    <label asp-for="Id" class="col-sm-3 control-label"></label>
                    <div class="col-sm-6">
                        <input asp-for="Id" class="form-control" readonly="readonly" />
                    </div>
                </div>
                @{
                    Html.RenderPartial("_MugOrder");
                }
                <div class="form-group">
                    <label class="col-sm-3 control-label">Subtotal: </label>
                    <div class="col-sm-6" style="padding-right:15px">
                        <input id="txtSubtotal" class="form-control" readonly="readonly" value="@String.Format("{0:0.00}", Model.Qty * 10)" />
                    </div>
                    <div class="col-sm-1" style="padding-left:0">
                        @{
                            Html.RenderPartial("_MugCurrencySelector");
                        }
                    </div>

                </div>
                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-10">
                        <input type="submit" value="Update" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div id="divPreview" class="col-sm-5">
        <img id="imgMug" src="~/images/mug.png" style="position:absolute;left:0;top:0;width:300px;height:300px;background-color:@Model.Color" />
        <img id="imgPoke" src="@String.Format(@"/images/{0}-200.png",Model.PokedexId)" style="position:absolute;left:20px;top:70px;height:180px;width:180px" />
    </div>

</div>