P13/Controllers/MembershipController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using P13.Models;
using Microsoft.EntityFrameworkCore;
using System.Dynamic;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace P13.Controllers
{
    public class MembershipController : Controller
    {
        private AppDbContext _dbContext;

        public MembershipController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
			DbSet<Member> dbs = _dbContext.Member;
            List<Member> model = dbs.ToList();
            return View(model);
        }

		public IActionResult Update(int id)
		{
			// To be implemented: Follow the requirments stated below:
			// Assuming id = 186
			// 1. If the member with id cannot be found then redirect to index action with message "Member 186 not found!"
			// 2. If the member with id can be found then
			//    a. Prepare a list of text and value for the purpose of allowing selection of happiness levels. The value maps to Id while text maps to Level of each HappinessLevel object. This list should be stored in ViewData under the key "levels"
			//    b. Return the Update view and pass the found member object to it
			DbSet<Member> dbs = _dbContext.Member;
			Member member = dbs.Where(m => m.Id == id).FirstOrDefault();

			if (member == null)
			{
				TempData["Msg"] = String.Format("Member {0} not found!", id);
				return RedirectToAction("index");
			}
			else
			{
				DbSet<HappinessLevel> dbsHappinessLevels = _dbContext.HappinessLevel;
				var lstHappinessLevels = dbsHappinessLevels.OrderBy(o => o.Id).ToList().Select(o =>
				{
					dynamic n = new ExpandoObject();
					n.value = o.Id;
					n.text = o.Level;
					return n;

				}).ToList();
				ViewData["levels"] = lstHappinessLevels;
				return View(member);
			}




			// The code below has to be replaced

		}


		[HttpPost]
		public ActionResult Update(Member selMember)
		{
			// To be implemented: Follow the requirements stated in the worksheet

			// The code below has to be replaced
			if (ModelState.IsValid)
			{
				DbSet<Member> dbs = _dbContext.Member;
				Member member = dbs.Where(a => a.Id == selMember.Id).FirstOrDefault();
				if (member == null)
				{
					TempData["Msg"] = String.Format("Member {0} not found!", selMember.Id);
					return RedirectToAction("Index");
				}
				else
				{
					member.Name = selMember.Name;
					member.HappinessLevelId = selMember.HappinessLevelId;
					member.Phone = selMember.Phone;
					if (_dbContext.SaveChanges() == 1)
						TempData["Msg"] = String.Format("Mmeber {0} updated successsfully!", selMember.Id);
					else
						TempData["Msg"] = "Update failed";
				}
			}

			return RedirectToAction("Index");
		}

	}
}

P13/Views/Shared/_AddressInput.cshtml
@using P13.Models
@model Address

<div class="form-group">
    <label asp-for="Street" class="col-sm-2 control-label"></label>
    <div class="col-sm-6">
        <input asp-for="Street" class="form-control col-sm-6" type="text">
    </div>
</div>
<div class="form-group">
    <label asp-for="City" class="col-sm-2 control-label"></label>
    <div class="col-sm-6">
        <input asp-for="City" class="form-control col-sm-6" type="text">
    </div>
</div>
<div class="form-group">
    <label asp-for="State" class="col-sm-2 control-label"></label>
    <div class="col-sm-6">
        <input asp-for="State" class="form-control col-sm-6" type="text">
    </div>
</div>
<div class="form-group">
    <label asp-for="Postcode" class="col-sm-2 control-label"></label>
    <div class="col-sm-6">
        <input asp-for="Postcode" class="form-control col-sm-6" type="text">
    </div>
</div>
<div class="form-group">
    <label asp-for="Country" class="col-sm-2 control-label"></label>
    <div class="col-sm-6">
        <input asp-for="Country" class="form-control col-sm-6" type="text">
    </div>
</div>

P13/Views/Shared/_DemoLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery-validation/src/core.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script>
        $.ajaxSetup({ cache: false });
    </script>
    @RenderSection("ScriptSection", false)
</head>
<body>
    <div class="row">
        <div class="col-sm-offset-1 col-sm-10">
            <div class="row">
                <div class="container body-content col-sm-8">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
</body>
</html>

P13/Views/Shared/_ExerciseLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery-validation/src/core.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script>
        $.ajaxSetup({ cache: false });
    </script>
    @RenderSection("ScriptSection", false)
</head>
<body>
    <div class="row">
        <div class="col-sm-offset-1 col-sm-10">
            <div class="row">
                <div class="container body-content col-sm-8">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
</body>
</html>

P13/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Cache-Control" content="no-store" />
    <title>Problem 13 - Happiness Club @ViewData["Title"]</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <link href="~/lib/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <script src="~/lib/moment/min/moment.min.js"></script>
    <script src="~/lib/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>

    <style>
        .input-group-addon {
            cursor: pointer;
        }

        #BsDateTimePicker {
            cursor: pointer;
        }
    </style>
    <script type="text/javascript">
        $(function () {
            $('#BsDateTimePicker').datetimepicker({
                format: 'DD-MM-YYYY'
            });
        });
    </script>
    <script src="~/lib/jquery-validation/src/core.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script>
        $.ajaxSetup({ cache: false });
    </script>
    @RenderSection("ScriptSection", false)
</head>
<body>
    <div class="row">
        <div class="col-sm-2">
            <img src="~/images/logo.png" style="width:90%;height:90%;margin-left:10px;margin-top:20px" />
        </div>
        <div class="col-sm-10">
            <div class="row">
                    <nav class="navbar navbar-default" role="navigation">
                        <div>
                            <ul class="nav navbar-nav">
                                <li class="active">
                                    <a asp-action="Index" asp-controller="Membership" class="menuItem">All Members</a>
                                </li>
                            </ul>
                        </div>
                    </nav>

                <div class="container body-content col-sm-8">
                        @RenderBody()
                </div>
                <div class="col-sm-1"></div>
            </div>
        </div>
    </div>
</body>
</html>

P13/Views/Shared/_OrderList.cshtml
@model List<Order>

@foreach (Order o in Model)
{
    <tr>
        <td>@o.OrderId</td>
        <td>@String.Format("{0:dd/MM/yyyy}",o.OrderDate)</td>
        <td>@o.Qty</td>
    </tr>

}

P13/Views/Shared/_ProductList.cshtml
@model List<Product>

@foreach (Product p in Model)
{
    <tr>
        <td>@p.Id</td>
        <td>@p.Description</td>
    </tr>

}