P12/Models/Patient.cs
using System;
using System.Collections.Generic;

namespace P12.Models
{
    public partial class Patient
    {
        public Patient()
        {
            Appointment = new HashSet<Appointment>();
        }

        public string Id { get; set; }
        public string Icpassport { get; set; }
        public string Name { get; set; }
        public int Citizenship { get; set; }

        public virtual ICollection<Appointment> Appointment { get; set; }
    }
}

P12/Controllers/AppointmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using P12.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace P12.Controllers
{
    public class AppointmentController : Controller
    {
        private AppDbContext _dbContext;

        public AppointmentController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [Authorize]
        public IActionResult Index()
        {
            DbSet<Appointment> dbs = _dbContext.Appointment;
            List<Appointment> model = dbs.OrderBy(a => a.AppDate)
                                           .ThenBy(a => a.PatientId)
                                           .ToList();
            return View(model);
        }

        [Authorize]
        public IActionResult Create(string Id)
        {
            DbSet<Patient> dbs = _dbContext.Patient;
            Patient patient = dbs.Where(p => p.Id == Id)
                                 .FirstOrDefault();
            if (patient == null)
            {
                TempData["Msg"] = String.Format("Patient {0} not found!", Id);
                return RedirectToAction("Index");
            }
            else
            {
                ViewData["patient"] = patient;
                Appointment model = new Appointment();
                model.PatientId = patient.Id;
                model.AppDate = DateTime.Today;
                return View(model);
            }
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(Appointment newAppointment)
        {
            DbSet<Appointment> dbs = _dbContext.Appointment;
            dbs.Add(newAppointment);

            int result = _dbContext.SaveChanges();
            if (result == 1)
            {
                TempData["Msg"] = String.Format("New appointment created for {0} created!", newAppointment.PatientId);
            }
            else
            {
                TempData["Msg"] = String.Format("Failed to create new appointment for {0}!", newAppointment.PatientId);
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult SearchByPatientId(string Id)
        {
            DbSet<Appointment> dbs = _dbContext.Appointment;
            List<Appointment> model = dbs.Where(a => a.PatientId == Id)
                                         .OrderBy(a => a.AppDate)
                                         .ThenBy(a => a.PatientId)
                                         .ToList();
            ViewData["byPatient"] = true;
            ViewData["patientId"] = Id;
            return View(model);
        }

        [Authorize]
        public IActionResult GetApptByPatientId(string Id)
        {
            DbSet<Appointment> dbs = _dbContext.Appointment;
            IQueryable<Appointment> q = from a in dbs
                                        where a.PatientId == Id
                                        orderby a.AppDate, a.PatientId
                                        select a;
            List<Appointment> model = dbs.Where(a => a.PatientId == Id)
                                         .OrderBy(a => a.AppDate)
                                         .ThenBy(a => a.PatientId)
                                         .ToList();
            ViewData["byPatient"] = true;
            return PartialView("_Appointments", model);
        }

        [Authorize]
        public IActionResult SearchByDate(string Id)
        {
            DateTime appt;
            List<Appointment> model;
            if (Utils.TryParseDate(Id, out appt))
            {
                DbSet<Appointment> dbs = _dbContext.Appointment;
                model = dbs.Where(a => a.AppDate == appt)
                                        .OrderBy(a => a.PatientId)
                                        .ToList();
            }
            else
            {
                model = new List<Appointment>();
            }

            ViewData["byPatient"] = false;
            ViewData["apptDate"] = Id;
            return View(model);
        }

        [Authorize]
        public IActionResult GetApptByDate(string Id)
        {
            DateTime appt;
            List<Appointment> model;
            if (Utils.TryParseDate(Id, out appt))
            {
                DbSet<Appointment> dbs = _dbContext.Appointment;
                model = dbs.Where(a => a.AppDate == appt)
                           .OrderBy(a => a.PatientId)
                           .ToList();
            }
            else
            {
                model = new List<Appointment>();
            }

            ViewData["byPatient"] = false;
            return PartialView("_Appointments", model);
        }
    }
}

P12/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using P12.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace P12.Controllers
{
    public class PatientController : Controller
    {
        private AppDbContext _dbContext;
        private IHostingEnvironment _env;

        public PatientController(AppDbContext dbContext, IHostingEnvironment environment)
        {
            _dbContext = dbContext;
            _env = environment;
        }

        [Authorize]
        public IActionResult Index()
        {
            DbSet<Patient> dbs = _dbContext.Patient;
            List<Patient> model = dbs.OrderBy(p => p.Id)
                                     .ToList();
            return View(model);
        }

        [Authorize]
        public IActionResult Update(string id)
        {
            DbSet<Patient> dbs = _dbContext.Patient;
            Patient tPatient = dbs.Where(p => p.Id == id)
                                  .FirstOrDefault();

            if (tPatient != null)
            {
                return View(tPatient);
            }
            else
                TempData["Msg"] = "Patient not found!";

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize]
        public IActionResult Update(Patient patient,
                                  IFormFile photo)
        {
            if (ModelState.IsValid)
            {
                DbSet<Patient> dbs = _dbContext.Patient;
                Patient tPatient = dbs.Where(p => p.Id == patient.Id)
                                      .FirstOrDefault();

                if (tPatient != null)
                {
                    tPatient.Name = patient.Name;
                    tPatient.Citizenship = patient.Citizenship;
                    tPatient.Icpassport = patient.Icpassport;

                    string msg = "";
                    if (_dbContext.SaveChanges() == 1)
                        msg = "Patient info updated. ";

                    // To be implemented：Save image if photo is not null
                    // Use 6P Part 1 slides to help complete this part

                    TempData["Msg"] = msg;
                }
                else
                    TempData["Msg"] = "Patient not found!";

            }
            else
                TempData["Msg"] = "Invalid input!";

            return RedirectToAction("Index");
        }

        private bool UploadFile(IFormFile ufile, string fname)
        {
            if (ufile.Length > 0)
            {
                string fullpath = Path.Combine(_env.WebRootPath, fname);
                using (var fileStream =
                           new FileStream(fullpath, FileMode.Create))
                {
                    ufile.CopyTo(fileStream);
                }
                return true;
            }
            return false;
        }

    }
}

P12/Views/Patient/Index.cshtml
@using P12.Models
@model List<Patient>

@{
    ViewBag.Title = "All Patients";    
}

<h2>All Patients</h2>

<span style="color:red">@TempData["Msg"]</span><br />
<table class="table table-bordered table-condensed table-hover table-striped">
    <tr>
        <th>Patient Id</th>
        <th>IC/Passport No.</th>
        <th>Name</th>
        <th>Citizenship</th>
        <th>Action</th>
    </tr>
    @foreach (Patient patient in Model)
    {
        <tr>
            <td><a asp-controller="Patient" asp-action="Update" asp-route-id="@patient.Id">
                    @patient.Id
                </a></td>
            <td>@patient.Icpassport</td>
            <td>@patient.Name</td>
            <td>@if (patient.Citizenship == 1)
            {
                <text>SPR</text>
            }
            else if (patient.Citizenship == 2)
            {
                <text>Singapore Citizen</text>
            }
            else
            {
                <text>Foreign</text>
            }
            </td>
            <td><a asp-controller="Appointment" asp-action="Create" asp-route-id="@patient.Id">Create Appointment</a></td>
        </tr>
    }
</table>

P12/Views/Patient/Update.cshtml
@using P12.Models
@model Patient

@{
    ViewBag.Title = "Update Patient Profile";
}

<h2>Update Patient Profile</h2>

<div class="row">
    <div class="col-sm-8">
        <form asp-controller="Patient" asp-action="Update"
              method="post" enctype="multipart/form-data"
              class="form-horizontal" role="form">
            <div class="form-horizontal">
                <!-- To be implemented: Complete the input blocks for Id (read-only), Name, Citizenship and Icpassport. Except read-only field all other fields should display proper validation messages -->
                <div class="form-group">
                    <label asp-for="Id" class="col-sm-4 control-label"></label>
                    <div class="col-sm-6">
                        <input asp-for="Id" class="form-control" readonly="readonly" />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="col-sm-4 control-label"></label>
                    <div class="col-sm-6">
                        <input asp-for="Name" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Icpassport" class="col-sm-4 control-label"></label>
                    <div class="col-sm-6">
                        <input asp-for="Icpassport" class="form-control"  />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Citizenship" class="col-sm-4 control-label"></label>
                    <div class="col-sm-6">
                        <input asp-for="Citizenship" class="form-control"  />
                    </div>
                </div>
                <!-- To be implemented: Add input element to upload file -->
                <div class="form-group">
                    <label class="col-sm-4 control-label">Photo:</label>
                    <div class="col-sm-6">
                        <input type="file" name="photo" class="form-control" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-10">
                        <input type="submit" value="Update" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div id="divPreview" class="col-sm-offset-1 col-sm-3">
        <img src="~/patient_images/@String.Format("{0}.png",Model.Id)" alt="No picture uploaded" class="table-bordered" style="position:absolute;left:50px;top:0px;width:200px;" />
    </div>
</div>