P11/Controllers/HESSAPController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using P11.Models;
using Microsoft.EntityFrameworkCore;
using System.Data.Common;
using System.Data.SqlClient;
using System.Dynamic;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace P11.Controllers
{

    public class HESSAPController : Controller
    {
        private AppDbContext _dbContext;

        public HESSAPController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        private Student curStudent()
        {
            var userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            DbSet<Student> dbs = _dbContext.Student;
            Student student = dbs.Where(s => s.Id == Int32.Parse(userid)).FirstOrDefault();
            return student;
        }

        // GET: HESSAP
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ViewResult()
        {
            //prepare model
            AcadPerfViewer model = new AcadPerfViewer();

            model.CurrentStudent = curStudent();
            model.Semester = 0;
            model.AcadResult = new List<Result>();

            if (model.CurrentStudent.IsAdmin)
            {
                DbSet<Student> dbs = _dbContext.Student;
                var lstStudents =
                    dbs.OrderBy(s => s.Id)
                       .ToList()
                       .Select(
                           s =>
                           {
                               dynamic d = new ExpandoObject();
                               d.value = s.Id;
                               d.text = $"{s.Id} {s.Name}";
                               return d;
                           }
                       )
                       .ToList<dynamic>();
                ViewData["students"] = lstStudents;
            }

            if (User.IsInRole("Admin"))
            {
                ViewData["semesters"] = new List<dynamic>();
            }
            else
            {
                DbSet<Result> dbsS = _dbContext.Result;
                var lstSemesters = dbsS.Where(s => s.StudentId == curStudent().Id)
                                             .OrderBy(s => s.Semester)
                                             .GroupBy(s => s.Semester)
                                             .Select(g => g.Key)
                                             .ToList()
                                             .Select(
                                                s =>
                                                   {
                                                       dynamic d = new ExpandoObject();
                                                       d.value = s;
                                                       d.text = s;
                                                       return d;
                                                   }
                                              )
                                              .ToList();
                ViewData["semesters"] = lstSemesters;
            }

            return View(model);
        }

        [Authorize]
        public IActionResult GetResult(int Id, int Semester)
        {
            DbSet<Result> dbs = _dbContext.Result;
            List<Result> model = dbs.Where(r => r.StudentId == Id &&
                                   r.Semester == Semester)
                       .OrderBy(r => r.ModuleId)
                       .Include("Module")
                       .ToList();

            return PartialView("_ResultsTable", model);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult AddResult()
        {
            DbSet<Student> dbsStudent = _dbContext.Student;
            var lstStudents =
                dbsStudent.OrderBy(s => s.Id)
                          .ToList()
                          .Select(
                            s =>
                               {
                                   dynamic d = new ExpandoObject();
                                   d.value = s.Id;
                                   d.text = $"{s.Id} {s.Name}";
                                   return d;
                               }
                           )
                          .ToList<dynamic>();
            ViewData["students"] = lstStudents;

            DbSet<Module> dbsModule = _dbContext.Module;
            var lstModules =
                dbsModule.OrderBy(m => m.Id)
                         .ToList()
                         .Select(
                            m =>
                            {
                                dynamic d = new ExpandoObject();
                                d.value = m.Id;
                                d.text = $"{m.Id} {m.Description}";
                                return d;
                            }
                          )
                           .ToList<dynamic>();
            ViewData["modules"] = lstModules;
            return View();
        }

        [HttpPost]
        public IActionResult AddResult(Result result)
        {
            string msg = "";
            Result model = result;
            if (ModelState.IsValid)
            {
                // To be implemented: Search in database to check whether the result of this module has been added before for the selected student
                // HINT: Query against _dbContext.Result
                // HINT: Use Where and FirstOrDefault method to check whether such result exists or not

                // To be implemented:
                // If such result is found in database, display message
                //      "Semester result for this module has been added before!"
                // If such result is not found then proceeds to insert the record
                // HINT: Use Add and SaveChanges method to insert
                // If insert is successful display:
                //      "New result added successfully
                // IF insert fails display:
                //      "Failed to update database"
            }
            else
            {
                msg = "Invalid information entered";
            }
            ViewData["msg"] = msg;

            // To be implemented: prepare ViewData["students"] and ViewData["modules"]
            // HINT: Refer to AddResult HttpGet action

            return View(model);
        }
    }
}

P11/Views/HESSAP/AddResult.cshtml
@model Result
@{

    ViewBag.Title = "Add Student Result";

    var students = ViewData["students"] as List<dynamic>;
    students.Insert(0, new { value = "0", text = "-- SELECT --" });

    var modules = ViewData["modules"] as List<dynamic>;
    modules.Insert(0, new { value = "0", text = "-- SELECT --" });

    string msg = ViewData["msg"] as string;
}



<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-sm-8">
        <form asp-controller="HESSAP" asp-action="AddResult" method="post" class="form-horizontal" role="form">
            @if (msg != null)
            {
                <div class="form-group">
                    <div class="col-sm-9">
                        <div class="alert alert-danger">
                            <strong>@msg</strong>
                        </div>
                    </div>
                </div>
            }
            <div class="form-group">
                <label asp-for="StudentId" class="col-sm-3 control-label">
                    Student
                </label>
                <div class="col-sm-6">
                    <select class="form-control col-sm-6"
                            asp-for="StudentId">
                        @foreach (var item in students)
                        {
                            <option value="@item.value">@item.text</option>
                        }
                    </select>
                </div>
                <div class="has-error">
                    <span asp-validation-for="StudentId" class="text-danger"></span>
                </div>
            </div>
            
            <!-- To be implemented: Complete the input blocks for Semester, ModuleId and Grade -->

            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </form>
    </div>
</div>

P11/Views/HESSAP/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Welcome to HES Students Academic Portal</h2>

<div style="font-family:Garamond;font-size:larger">
   <b>HES Students Academic Portal</b>, a self-service portal for HES students to view results online.
</div>

P11/Views/HESSAP/ViewResult.cshtml
@using System.Security.Claims
@model AcadPerfViewer
@{
    ViewBag.Title = "Academic Performance Viewer";
    dynamic students = null;

    if (ViewData["students"] != null)
    {
        students = ViewData["students"] as List<dynamic>;
        students.Insert(0, new { value = "0", text = "-- SELECT --" });
    }

    var semesters = ViewData["semesters"] as List<dynamic>;
    semesters.Insert(0, new { value = "0", text = "-- SELECT --" });
}

@section ScriptSection {
    <script>
        function loadSemesters() {
            var studentId = $("#ddlStudent").val();
            var apiUrl = "/api/HESSAP/Semesters/" + studentId;
            var ddlSemester = $("#ddlSemester");

            //To be implemented: Use $.getJSON to load semesters into ddlSemester and call loadResult function after that
        }

        function loadResult() {
            var semester = $("#ddlSemester").val();

            if (semester > 0) {
                var studentId = $("#ddlStudent").val();
                var ajaxUrl = "/HESSAP/GetResult/" + studentId + "?Semester=" + semester;

                //To be implented: Update the results table using partial view
                //Hint: Note that divResultsPanel can be hidden at this point
            }
            else {
                //To be implemented: Hide divResultPanel
            }
        };

         $(document).ready(function () {
            //To be implemented: Hide divResultsPanel

             $("#ddlStudent").change(function () {
                loadSemesters();
            });


            $("#ddlSemester").change(function () {
                loadResult();
            });
        });
    </script>
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-sm-7">
        <form asp-controller="ShirtOrder" asp-action="Create" method="post" class="form-horizontal" role="form">
            <div class="form-group">
                <label asp-for="CurrentStudent.Id" class="col-sm-3 control-label">
                    Student
                </label>
                <div class="col-sm-6">
                    <select id="ddlStudent" class="form-control col-sm-6"
                            asp-for="CurrentStudent.Id">
                        @if (User.IsInRole("Admin"))
                        {
                            @foreach (var item in students)
                            {
                                <option value="@item.value">@item.text</option>
                            }
                        }
                        else
                        {
			    var userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                            <option value="@userid">@userid</option>
                        }
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Semester" class="col-sm-3 control-label">
                    Semester
                </label>
                <div class="col-sm-6">
                    <select id="ddlSemester" class="form-control"
                            asp-for="Semester">
                        @foreach (var item in semesters)
                        {
                            <option value="@item.value">@item.text</option>
                        }
                    </select>
                </div>
            </div>
            <div id="divResultsPanel" class="form-group">
                <label for="divResults" class="col-sm-3 control-label">
                    Acad Results
                </label>
                <div id="divResults" class="col-sm-9">
                    @{
                        Html.RenderPartial("_ResultsTable", Model.AcadResult);
                    }
                </div>
            </div>
        </form>
    </div>
</div>